version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/root/db
    environment:
      - SQLITE_DATABASE=bios.db